### ISSUE TITLE
Update command allows duplicate event to be created

### ISSUE THREAD

**Issue by Gilbb** [AY2425S1-CS2103T-T10-4/tp#146]
## Description
The update command allows duplicate event to be created

## Steps to Reproduce
Create an event: `event -n New Year's Party -d 2025-01-01 -l Times Square -a 1 2 4 5`
Create another event with only difference in attendee: `event -n New Year's Party -d 2025-01-01 -l Times Square -a 1 2 4`
Remove attendee 5 from event 1: `update -i 1 -r 5`
Exit the application.
Boot up the application.

## Expected Behavior
The update command should not allow removing of attendee 5 since it causes a duplicate event.

## Screenshots
![image](https://github.com/user-attachments/assets/cb4f91cf-1236-4a65-8749-6aacda9505b2)
![image](https://github.com/user-attachments/assets/6b6e19c1-6e80-4846-9f6b-073e117d8d14)

**Comment by michaelyql** [comment]
Should add test case for update command: update_duplicateEvent_errorThrown

**Comment by marchjlim** [comment]
Instead of fixing it by preventing someone from updating an event into a duplicate event, I thought that it would be better to prevent such similar events to be created in the first place.

If events are the same in every aspect other than attendees, I think it is reasonable to say that they are the same events.

However, there are some gray areas that make me feel uncertain whether this is the correct implementation. If the location is very vague, it is valid to say that two events with the 'same' location can be different events.

For example,
'House party' at 'NUS' with attendees 1 2 3 can be different from
'House party' at 'NUS' with attendees 4 5 6

because NUS is such a broad location name, it can result in two different events being held at different parts of NUS.
